baseURL = "https://authors.pubs.vensel.org"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Author Hub - Vensel Publications"
theme = "docdock"
# themesdir = "/home/deepak/Documents/venselinstructions/author-instructions/themes"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false


[Languages]
[Languages.en]
title = "Author instructions"
weight = 1
languageName = "English"


[markup]
[markup.goldmark.renderer]
unsafe = true

[params]
showVisitedLinks = true # default is false
themeStyle = "original" # "original" or "flex" # default "flex"
themeVariant = "gray" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = true # set true to open shortcuts links to a new tab/window
enableGitInfo = false

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
name = "<i class='fa-solid fa-book-open'></i> <label>Journals</label>"
url = "https://pubs.vensel.org"
weight = 11
